### ISSUE TITLE
Stuck on bypassing (requests need to be installed through pip)

### ISSUE THREAD

**Issue by wixglo** [paulo27ms/1fichier-dl-customproxies#2]
I'm unable to launch the app, through vbs file and even through the command "python 1fichier-dl/gui.py" I get this error :
`Traceback (most recent call last):
  File "C:\Users\raph\Desktop\divers\1fichier-dl-customproxies-main\1fichier-dl\gui.py", line 3, in <module>
    from core.gui import gui
  File "C:\Users\raph\Desktop\divers\1fichier-dl-customproxies-main\1fichier-dl\core\gui\gui.py", line 7, in <module>
    from ..download.workers import FilterWorker, DownloadWorker
  File "C:\Users\raph\Desktop\divers\1fichier-dl-customproxies-main\1fichier-dl\core\download\workers.py", line 2, in <module>
    from .download import *
  File "C:\Users\raph\Desktop\divers\1fichier-dl-customproxies-main\1fichier-dl\core\download\download.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

And I performed the installation of the packages, as pip list shows me they are correctly installed.
I use python 3.9.7.

EDIT : You forgot to mention that requests need to be installed through pip. I fixed my problem by installing it. But now, the program stuck on "bypassing" for a long time.

**Comment by ghost** [comment]
Thanks! Installing request through pip fixed my issues.

**Comment by paulo27ms** [comment]
Sorry about that, apparently I don't get notification by default for my own fork...
I updated the requirements.txt to reflect this. I just did it on a clean install and I believe there's no other dependency on this.

Regarding the bypassing issue, this is likely an issue with the proxy list you're using or if you aren't using any list, an issue on proxyscan.
Could you share the list to analyze if you're still having issues?

**Comment by 0megaplus** [comment]
Excuse me, but I'm having a similar issue. I've entered the folder, and ran `pip install -r requirements.txt`, but this appears:

` Traceback (most recent call last):
        File "C:\Users\typho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\sipbuild\api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\sipbuild\project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-install-qu4a37dp\pyqt5_3b379426e04642dc8814c798a7fe9875\project.py", line 64, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\sipbuild\project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-jtqmdsdd\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException`
Can anybody help? This app would be awesome if I could get it working.

**Comment by paulo27ms** [comment]
Can you try updating your pip version and see if install it the requirements works afterwards?

**Comment by paulo27ms** [comment]
Also, if that doesn't fix it then try to change the version on the .txt file to 5.15.2.
Let me know what fixes it.

**Comment by 0megaplus** [comment]
I have updated to the latest version of pip on CMD, as well as changing the .txt file version to 5.15.2, but nothing helped. 
Does it help if I mention it says, `This is an issue with the package mentioned above, not pip`, and `This error originates from a subprocess, and is likely not a problem with pip`?

**Comment by paulo27ms** [comment]
You can also try to remove PyQt5 from the requirements and install normally through pip with ``pip install pyqt5``... This is some issue either with the Python version from the Windows Store (I'm assuming that's what you're using) or just a recent Python update in general.

**Comment by 0megaplus** [comment]
Okay, I installed both PyQt5 and LXML via the regular `pip install` commands. This worked.
Thanks for your help!

**Comment by LuckyPants12** [comment]
```C:\Users\vivaa\Desktop\1fichier-dl-customproxies>pip install -r requirements.txt
Collecting PyQt5==5.15.1
  Using cached PyQt5-5.15.1.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\vivaa\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\vivaa\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\vivaa\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\vivaa\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\sipbuild\project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-install-wt5banha\pyqt5_4aa1d8525090421f80c358209caffd4f\project.py", line 64, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\vivaa\AppData\Local\Temp\pip-build-env-6scllj4p\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\vivaa\Desktop\1fichier-dl-customproxies>
```

i am still getting a simmilar error i cant seem to install *lxml==4.6.1* at all

**Comment by 0megaplus** [comment]
You've tried installing it normally without using the dependencies text file or any of the other ideas?

**Comment by LuckyPants12** [comment]
> You've tried installing it normally without using the dependencies text file or any of the other ideas?

yeah i have tried installing individually but while installing any dependency the same error i think pops up
``pip install lxml==4.6.1`` 
Gives error
``pip install lxml``
says requirement alredy satisfied

same for the other if i specifiy a version it faild and if i dont then it says its alredy installed

**Comment by paulo27ms** [comment]
And you can't open the program still?
Unfortunately this is more an error related to your python installation or pip issue more than anything and is harder to figure out.

**Comment by 0megaplus** [comment]
If the requirement was already satisfied, then try to continue with the rest of the requirements listed on the txt. Can you install the other requirements? Try opening the .vbs file afterwards.

**Comment by LuckyPants12** [comment]
> And you can't open the program still? Unfortunately this is more an error related to your python installation or pip issue more than anything and is harder to figure out.

I dont know what to do then really...


> If the requirement was already satisfied, then try to continue with the rest of the requirements listed on the txt. Can you install the other requirements? Try opening the .vbs file afterwards.

Well i tried everything i could install individuallly, it still wont open

**Comment by 0megaplus** [comment]
Hmm, I'm not totally sure what to do. You could try uninstalling pip and reinstalling it, try updating your pip to the latest version, or fix your python somehow (maybe by reinstalling it or something similar).
