### ISSUE TITLE
(Solved) Unable to execute vbs

### ISSUE THREAD

**Issue by jfv00** [paulo27ms/1fichier-dl-customproxies#6]
I just installed Python 3.11, and got this message after running "pip install -r requirements.txt".

I have run the following commands afterwards:

> pip install pyqt5
> pip install lxml
> pip install requests

The vbs interface now works fine.

```
C:\1fichier>pip install -r requirements.txt
Collecting PyQt5==5.15.1
  Using cached PyQt5-5.15.1.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\John\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\John\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\John\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\John\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\sipbuild\project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\John\AppData\Local\Temp\pip-install-h7bazly8\pyqt5_2ef180eb5405472eb6f52ae93fd3a758\project.py", line 64, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\John\AppData\Local\Temp\pip-build-env-dx1qwaw7\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by paulo27ms** [comment]
This seems like an install error for PyQt5. Unfortunately  there's not much help I can provide.

**Comment by jfv00** [comment]
> This seems like an install error for PyQt5. Unfortunately there's not much help I can provide.

Through tryal and error (and in my first time using python ever XD) I found the solution, and wrote it above for anyone who may need help ;)
